### ISSUE TITLE
Article: "Common Rx issues and how to solve it" 

### ISSUE THREAD

**Issue by Char0394** [RLittlesII/rodneylittlesii#5]
There are a lot of issues that we can face using Rx, would be really helpful to have a compilation of the most commons in a blog post.

**Comment by RLittlesII** [comment]
[Advanced Rx and Dragons](https://www.youtube.com/watch?v=W0VwW3IGsJc) by Michael Stonis gives a good run down of things to consider.

I will gladly draft an article on some common things I have seen that cause trouble when learning Rx.

**Comment by RLittlesII** [comment]
- [ ] Subscribe to an observable

- [ ] Throttle input

- [ ] Defer subscription

- [ ] Compose

- [ ] Creation

**Comment by RLittlesII** [comment]
Resolved: 7dacdca5ea6c383d932412664ab2e37157eb1482
